### ISSUE TITLE
setup.py develop not working

### ISSUE THREAD

**Issue by TimDettmers** [uclmr/jack#323]
I did:
`pip install -r requirements.txt`
`pip uninstall tensorflow`
`pip install tensorflow-gpu`
Since jack does not work with tensorflow-gpu only, I did:
`pip install tensorflow`
Running `python setup.py develop` yields:
```python
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    packages=find_packages())
  File "/home/tim/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/tim/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/tim/anaconda3/lib/python3.6/distutils/dist.py", line 972, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/home/tim/anaconda3/lib/python3.6/distutils/dist.py", line 847, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)

```

**Comment by pminervini** [comment]
I'm doing this at the moment, for testing/running `jack` on machines with GPUs:

```shell
$ python3 -m pip install -r requirements.txt --upgrade
$ python3 -m pip install tensorflow-gpu
$ python3 setup.py install
```

**Comment by pminervini** [comment]
Now installing works like this:

```bash
$ pip install -e .[tf]
or
$ pip install -e .[tf_gpu]
```

**Comment by riedelcastro** [comment]
That's great!

**Comment by pminervini** [comment]
should we release `jack` on PyPI [1] ?

[1] https://pypi.python.org/pypi

**Comment by riedelcastro** [comment]
That would be great! So we could write `pip install jack`?
