### ISSUE TITLE
Pretrained FastQA gives KeyError: 'model'

### ISSUE THREAD

**Issue by minttusofia** [uclmr/jack#332]
I tried using pretrained FastQA as described in the README, but hit this error:

```
$ python3 ./fastqa_test.py
Traceback (most recent call last):
  File "./fastqa_test.py", line 4, in <module>
    fastqa_reader = readers.reader_from_file("./fastqa_reader")
  File "/Users/minttu/src/python/nlp/project/jack/jack/readers/implementations.py", line 46, in reader_from_file
    reader = readers[shared_resources.config["model"]](shared_resources)
KeyError: 'model'
```

when running the example use case:

```
from jack import readers
from jack.core import QASetting

fastqa_reader = readers.reader_from_file("./fastqa_reader")

support = """"It is a replica of the grotto at Lourdes, 
France where the Virgin Mary reputedly appeared to Saint Bernadette Soubirous in 1858. 
At the end of the main drive (and in a direct line that connects through 3 statues and the Gold Dome), 
is a simple, modern stone statue of Mary."""

answers = fastqa_reader([QASetting(
    question="To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?",
    support=[support]
)])
```

**Comment by riedelcastro** [comment]
Was there a change in the name of the 'model' configuration parameter?

**Comment by dirkweissenborn** [comment]
this is a bug in the README while unzipping the model. Sorry for that. Please run the following to fix this issue:

```bash
rm -r fastqa_reader
unzip fastqa.zip && mv fastqa fastqa_reader
```

**Comment by minttusofia** [comment]
Thank you, that fixed it.
