### ISSUE TITLE
Embedding paths do not affect load directory?

### ISSUE THREAD

**Issue by TimDettmers** [uclmr/jack#340]
I `reader_from_file` the `embedding_file` path is set, but always the same directory is selected for the embeddings:
```=python
Traceback (most recent call last):
  File "qa.py", line 22, in <module>
    reader = reader_from_file("remqa_reader")
  File "/home/tim/anaconda3/lib/python3.6/site-packages/jack-0.1.0-py3.6.egg/jack/readers/implementations.py", line 45, in reader_from_file
  File "/home/tim/anaconda3/lib/python3.6/site-packages/jack-0.1.0-py3.6.egg/jack/core/shared_resources.py", line 62, in load
  File "/home/tim/anaconda3/lib/python3.6/site-packages/jack-0.1.0-py3.6.egg/jack/util/vocab.py", line 247, in load
  File "/home/tim/anaconda3/lib/python3.6/site-packages/jack-0.1.0-py3.6.egg/jack/io/embeddings/embeddings.py", line 74, in load_embeddings
  File "/home/tim/anaconda3/lib/python3.6/site-packages/jack-0.1.0-py3.6.egg/jack/io/embeddings/memory_map.py", line 24, in load_memory_map_dir
FileNotFoundError: [Errno 2] No such file or directory: 'data/GloVe/glove.840B.300d.memory_map_dir/meta.json'

```

**Comment by dirkweissenborn** [comment]
the embedding file path is set in the shared resources. If you want to change it, take a look at `remqa_reader/shared_resources_vocab/conf.yaml` . We still have embeddings and vocab coupled which should be resolved soon #337 (hopefully).
